<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
    <UmbracoVersion Condition="'$(UmbracoVersion)' == ''">[17.1.0,19.0.0)</UmbracoVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="ContentAuthenticity" Version="0.90.16" />
    <PackageVersion Include="Umbraco.Cms.Web.Common" Version="$(UmbracoVersion)" />
    <PackageVersion Include="Umbraco.Cms.Api.Management" Version="$(UmbracoVersion)" />
    <PackageVersion Include="MailKit" Version="4.17.0" />
    <PackageVersion Include="MessagePack" Version="3.1.8" />
    <PackageVersion Include="Microsoft.OpenApi" Version="2.12.2" />
    <PackageVersion Include="MimeKit" Version="4.17.0" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="10.0.10" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
